name = "osmos-landing"
compatibility_date = "2026-01-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "osmos-questionarios"
database_id = "6bad8a35-3b38-4c18-a01c-209d50e10d60"
